### ISSUE TITLE
Use HTTPS for external dependencies

### ISSUE THREAD

**Issue by bfontaine** [resume/resume.github.com#182]
YUI & jQuery should be loaded over HTTPS to prevent Chrome from blocking them when viewing the page with HTTPS.

```
[blocked] The page at 'https://resume.github.io/?bfontaine' was loaded over HTTPS, but ran insecure content from 'http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css': this content should also be loaded over HTTPS.
[blocked] The page at 'https://resume.github.io/?bfontaine' was loaded over HTTPS, but ran insecure content from 'http://code.jquery.com/jquery-1.8.1.min.js': this content should also be loaded over HTTPS.
```

Steps to reproduce:

1. Open https://resume.github.io/?bfontaine
2. Nothing is displayed, there’s only the gray background

I’m using Chrome 34.0.1847.131 on OS X 10.9.2.

**Comment by u2** [comment]
I will merge #190 or #188. I'd prefer to `//`.

**Comment by cyphar** [comment]
@u2 I don't understand why people romanticise `//` (if someone loads our page insecurely, lets make them load **everything** insecurely). Anyway, `//` doesn't work for Yahoo (they don't support both HTTP and HTTPS for the same CDN URL).

**Comment by u2** [comment]
@cyphar I just read a [article](http://encosia.com/3-reasons-why-you-should-let-google-host-jquery-for-you/) about HTTPS. :)

>  HTTPS all the things
Note that the script reference above uses the HTTPS protocol. For years, the examples on this page used a protocol-relative reference, beginning with just `//` instead of `http://` or `https://`, and this section of the post described how that was not a typo and was actually a valid URL.
I no longer recommend that approach.
You should always use the HTTPS jQuery CDN reference, even if you’re including jQuery on a page that is itself being served via unencrypted HTTP. This greatly reduces the chances of someone tampering with the contents of the jQuery script between Google’s CDN servers and your users’ browsers. The overhead is minimal and all of the three benefits that I described earlier are still applicable when using the encrypted transport.

I will reopen #205. Could you rebase it?
