### ISSUE TITLE
Starred but show as not opt-in

### ISSUE THREAD

**Issue by lloydwatkin** [resume/resume.github.com#194]
Hi,

I've starred the repo (in fact its been starred for some time). But I'm showing as not opt'd in.
I've un-starred and re-stared to no-avail.

I'm working from home with my own public IP so I can't see me having hit any rate limits.

Cheers, Lloyd.

**Comment by fritz-fritz** [comment]
Hello, same issue on Safari. Seems no one has touched this project in a while.

```
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (starred, line 0)
https://api.github.com/users/{username}/starred?page=1
```

```
{
  "message": "API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

Upon further reading of the [developer documentation](https://developer.github.com/v3/#rate-limiting), it seems there is indeed a rate limit in effect. The headers reveal that I have 0 remaining un-authenicated API requests available until about a half hour from now. I would suggest handling this error case with a specific message instead of falling directly to the current "Not Opted In" message.

**Comment by u2** [comment]
Yes, it's because of the rate-limiting. We have added 403 page for this. #172
